[Ability][Checkup][Bug] Fixing up Fluffy's interactions with Long Reach + adding tests/utilities for Fluffy
Despair-Games/poketernity pull request #139
Opened 2024-12-28 06:24 UTC by frutescens

## What are the changes the user will see?

Fluffy should interact correctly with Long Reach now. 

## Why am I making these changes?

Ability Checkup + needed some better testing utilities for tracking base damage, post-multiplier/calculated damage, and final damage. 

## What are the changes from a developer perspective?

DamageCalculationResult now has the optional fields of baseDamage and postMultiplierDamage.
Fluffy now uses checkFlag() instead of hasFlag()

## How to test the changes?

`npm run test fluffy`
![image](https://github.com/user-attachments/assets/8748584b-f52f-4adc-829d-49dcad08c919)

## Checklist

- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test`)
  - [x] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?

2024-12-29 17:21 UTC, MokaStitcher requested changes
There are a number of tests that reference the now gone `DamageCalculationResult.damage`, and MoveEffectPhase itself has an error too

![image](https://github.com/user-attachments/assets/37947db8-8a18-477b-8c64-be9471d79096)

2025-01-05 21:16 UTC, PigeonBar commented on src/data/abilities.ts
>        .attr(ReceivedMoveDamageMultiplierAbAttr, (_target, user, move) => user.getMoveType(move) === Type.FIRE, 2)
```suggestion
      .attr(ReceivedTypeDamageMultiplierAbAttr, Type.FIRE, 2)
```
Just a minor simplification

2025-01-06 01:08 UTC, PigeonBar approved these changes

2025-01-06 13:50 UTC, MokaStitcher approved these changes

2025-01-06 13:51 UTC, merged