[Ability][Checkup] Added documentation and tests for Anger Point
Despair-Games/poketernity pull request #145
Opened 2024-12-29 04:15 UTC by frutescens

## What are the changes the user will see?

None.

## Why am I making these changes?

~~Looking for an easier ability to work on.~~ Ability checkups...

## What are the changes from a developer perspective?

Conditional changed to look at the whole of attacksReceived from an attacking Pokemon to address the bug where Anger Point fails to activate from multi-hit moves. 
Tests and documentation added. 

## How to test the changes?

`npm run test anger_point`

## Checklist

- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test`)
  - [x] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?

2024-12-29 16:02 UTC, MokaStitcher submitted a review, later dismissed

2024-12-29 17:57 UTC, Tempo-anon submitted a review, later dismissed

2024-12-30 21:06 UTC, PigeonBar commented
It turns out there is a bug where Anger Point does not activate if the defender gets hit with a critical hit _during a multi-hit move_:

https://github.com/user-attachments/assets/b1a39683-6d27-496a-a5f5-79c0dd115afb

To explain why this bug occurs, note that attacks get added to `attacksReceived` by calling `unshift()`, so attacks are stored in order from newest to oldest:

https://github.com/Despair-Games/poketernity/blob/121a348453a61754e4de29a266a689828fc7af0e/src/phases/move-effect-phase.ts#L458

On the other hand, Anger Point checks `attacksReceived[length - 1]`, which means that it incorrectly checks whether the first hit, rather than the most recent hit, is a critical hit:

https://github.com/Despair-Games/poketernity/blob/121a348453a61754e4de29a266a689828fc7af0e/src/data/ab-attrs/post-defend-crit-stat-stage-change-ab-attr.ts#L38-L41


<sup> Our codebase is cursed, there is no such thing as an "easier ability to work on" </sup>

2025-01-01 04:01 UTC, DayKev submitted a review, later dismissed

2025-01-01 14:27 UTC, PigeonBar commented
Separately, [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Anger_Point_(Ability)) states that Anger Point's activation should always max out the Pokemon's Attack stat. However, since Anger Point is implemented as raising Attack by 6 stages, there is a bug where the Pokemon's Attack doesn't get maxed out if it starts below 0.

https://github.com/Despair-Games/poketernity/blob/cc6f0b15da90290dd7e2e60a5d0b8be4af2bc3c9/src/data/abilities.ts#L581

I think changing the 6 to a 12 (matching Belly Drum's implementation) should fix this issue.

2025-01-04 17:43 UTC, PigeonBar commented on src/data/ab-attrs/post-defend-crit-stat-stage-change-ab-attr.ts
> +      && pokemon.summonData.statStages[Stat.ATK] < 6
```suggestion
      && pokemon.getStatStage(Stat.ATK) < 6
```

2025-01-04 17:44 UTC, PigeonBar commented
One more edge case (hopefully the last one) from testing: If a Pokemon's stat gets raised by 7 or more stages at once, the game displays "The Pokemon's stat cannot go any higher!" instead of "The Pokemon's stat rose drastically!"

https://github.com/Despair-Games/poketernity/blob/6f719c4d466b5aff95d351ceafb032985625041c/src/enums/stat.ts#L48-L57

2025-01-04 22:02 UTC, Tempo-anon requested changes, later dismissed

2025-01-04 22:02 UTC, Tempo-anon commented on src/enums/stat.ts
> +  } else if ((stages > 2 && stages <= 6) || (stages = BATTLE_STAT_MAX)) {
`stages === BATTLE_STAT_MAX`

2025-01-04 22:07 UTC, DayKev commented on src/enums/stat.ts
> +  } else if ((stages > 2 && stages <= 6) || (stages = BATTLE_STAT_MAX)) {
Why does this if exclude values above 6 anyway?

2025-01-05 03:32 UTC, PigeonBar commented on src/enums/stat.ts
> +  } else if ((stages > 2 && stages <= 6) || stages === BATTLE_STAT_MAX) {
This still sometimes doesn't work because the value of `stages` is the number that the Pokemon's stat stage actually changed by, instead of the number that the StatStageChangePhase tries to change the stat stage. For example, if Anger Point causes a Pokemon's Attack to increase from -3 to +6, the value of `stages` is 9, not 12.

I think the solution is to just remove the `stages <= 6` check here.

2025-01-05 20:29 UTC, PigeonBar commented
Sorry about all this trouble, but apparently the game is actually supposed to say "<Pokemon> maxed its Attack!" when Anger Point activates.

Source: [Youtube](https://youtu.be/XW-VJVEsbMo?si=mPFohowYUd_wodX-&t=297)

2025-01-05 20:31 UTC, PigeonBar approved these changes, later dismissed
At this point we should probably just slap on a `.edgeCase()` for the activation message and call it a day

2025-01-05 22:19 UTC, frutescens commented
It's all good. I added one in since it's not a major change + if not now, when?

https://github.com/user-attachments/assets/61ccd1c8-5369-4bc5-ab39-bc86582dc103

https://github.com/Despair-Games/poketernity-locales/commit/444243e0571b8881d83a1cd9d1ca0cc8dcf2666a

2025-01-06 01:43 UTC, PigeonBar commented on src/phases/stat-stage-change-phase.ts
> +          messages.concat(this.getStatStageChangeMessages(filteredStats, stages.value, relLevels));
```suggestion
          messages.push(...this.getStatStageChangeMessages(filteredStats, stages.value, relLevels));
```
(`.concat()` returns a new array without modifying any existing arrays)

2025-01-06 02:04 UTC, DayKev commented on test/abilities/anger_point.test.ts
> +  it("should activate multiple times if it receives multiple critical hits in a single turn", async () => {
This test is no longer relevant.

2025-01-06 02:24 UTC, PigeonBar approved these changes

2025-01-06 02:29 UTC, DayKev approved these changes

2025-01-06 02:39 UTC, merged