[Move] Fully Implement Sky Drop
Despair-Games/poketernity pull request #64
Opened 2024-12-17 12:07 UTC by innerthunder

## What are the changes the user will see?

[Sky Drop](https://bulbapedia.bulbagarden.net/wiki/Sky_Drop_(move)) will now carry the target up to the air and immobilize them.

## Why am I making these changes?

I just made Dragon Darts and wanted to enter a new level of hell

## What are the changes from a developer perspective?

- Sky Drop implemented with
  - new move attributes `SkyDropAttr` and `NoDamageAgainstFlyingAttr`. `SkyDropAttr` is implemented as a charge attribute
  - new `hitCheckOnCharge` flag for charge moves to force Sky Drop to calculate a hit check during the move's charge phase.
  - new battler tag `SkyDropTag` representing the airborne status from Sky Drop.
- New abstract phase `HitCheckPhase` contains the hit check calculation function as well as some related helper functions. This is now inherited by both `MoveChargePhase` and `MoveEffectPhase`, so both phases can make use of the function.
- Adjusted some code for Wimp Out, Commander, and Gravity to account for edge cases with Sky Drop.

## Screenshots/Videos

<details>
  <summary>Single Battle: Sky Drop executed over 2 turns </summary>

https://github.com/user-attachments/assets/a9d85bc3-d8e0-49aa-9964-27348c292ce0

</details>

<details>
<summary>Double Battle</summary>

https://github.com/user-attachments/assets/5c3e9b50-3eb9-4ea8-9e9e-6f310e843916

</details>

## How to test the changes?

`npm run test sky_drop` - new

`npm run test wimp_out` - 1 new test

![image](https://github.com/user-attachments/assets/d986b19f-0acd-4c03-a76c-d06b9a36229e)

## Checklist

- [x] **I'm using `beta` as my base branch**
- [x] There is no overlap with another PR?
- [x] The PR is self-contained and cannot be split into smaller PRs?
- [x] Have I provided a clear explanation of the changes?
- [x] Have I tested the changes manually?
- [x] Are all unit tests still passing? (`npm run test`)
  - [x] Have I created new automated tests (`npm run create-test`) or updated existing tests related to the PR's changes?
- [x] Have I provided screenshots/videos of the changes (if applicable)?
  - [n/a] Have I made sure that any UI change works for both UI themes (default and legacy)?

2024-12-18 09:41 UTC, DayKev approved these changes

2024-12-18 16:23 UTC, flx-sta reviewed
Code-review only

2024-12-21 07:32 UTC, DayKev approved these changes
![image](https://github.com/user-attachments/assets/a0a11655-ac09-415a-acef-c8a87bc22c95)
![image](https://github.com/user-attachments/assets/efb79a95-454c-4dd5-b151-e2d1b0b9f42c)

2024-12-22 15:32 UTC, MokaStitcher reviewed
have done no testing, just looked at part of the code but all brain power has left...
Still posting since i have some questions, sorry if they are silly

2024-12-26 10:48 UTC, DayKev submitted a review, later dismissed
![image](https://github.com/user-attachments/assets/45b45bf0-b8b4-4fb3-a6b9-76a83ceed4a6)
![image](https://github.com/user-attachments/assets/8a51b157-5b08-41b5-9ce9-7689571ad99b)

2025-01-05 17:19 UTC, DayKev approved these changes, later dismissed

2025-01-05 22:30 UTC, DayKev approved these changes, later dismissed

2025-01-08 21:40 UTC, DayKev submitted a review, later dismissed

2025-01-09 05:06 UTC, DayKev submitted a review, later dismissed

2025-01-09 15:45 UTC, flx-sta requested changes, later dismissed
Something is off with the animation in double-battles.
In my video it pulls up Tentacool in the animation but effectively chose Geodude:

https://github.com/user-attachments/assets/2bf5cc08-5efb-4608-99bb-ee974268270c

2025-01-10 21:29 UTC, flx-sta approved these changes, later dismissed
https://github.com/user-attachments/assets/fafb0d42-1159-4147-8e24-8b8dc9e36114

2025-01-10 22:01 UTC, DayKev commented on src/data/battle-anims.ts
> +   * **Note:** The default for {@linkcode targetIndex} being {@linkcode BattlerIndex.PLAYER} is due to MoveCharAnim originally not supporting a target argument.
```suggestion
   * **Note:** The default for {@linkcode targetIndex} being {@linkcode BattlerIndex.PLAYER} is due to `MoveChargeAnim` originally not supporting a target argument.
```

2025-01-10 22:02 UTC, DayKev approved these changes

2025-01-10 22:02 UTC, flx-sta approved these changes

2025-01-10 22:09 UTC, merged